### ISSUE TITLE
Priority Tracker

### ISSUE THREAD

**Issue by fire** [godot-extended-libraries/ewbik#18]
- [x] Fix axial constraints
- [x] See axial constraints
- [x] Test axial: Better to start with a test on the hammer that doesn't call the IK solver. Have all three bones pointing straight up, rolls one of them beyond the twist limit, then calls the snap to twist function to ensure that it does actually return to the expected position.
- [x] Rename shaders to the proper naming convention
- [x] Assign constraints onto the vrm skeleton

**Comment by fire** [comment]
All the issues are resolved.
